name: CI
on:
  push:
    branches:
      - devel
      - alpha
      - 'release/**'
  pull_request:
    branches:
      - devel
      - alpha
      - 'release/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install build-essential

      - name: Build
        run: make all

      - name: Reproducible build test
        run: |
          make erigon
          shasum -a256 ./build/bin/erigon > erigon1.sha256
          make erigon
          shasum -a256 ./build/bin/erigon > erigon2.sha256
          if ! cmp -s erigon1.sha256 erigon2.sha256; then
            echo >&2 "Reproducible build broken"; cat erigon1.sha256; cat erigon2.sha256; exit 1
          fi

      - name: Install golangci-lint
        if: runner.os == 'Linux'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          skip-build-cache: true
          args: --help

      - name: Install go-licenses
        if: runner.os == 'Linux'
        run: cd erigon-lib && make lint-licenses-deps

      - name: Lint
        if: runner.os == 'Linux'
        run: make lint

      - name: Test
        run: make test
