name: Nightly - ETH Bench

on:
  schedule:
    - cron: '0 1 * * *' # run at 1am to stagger tests
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: 
          includes:
            - profile_name: "network5"
              l1_ep: "https://rpc.eu-central-1.gateway.fm/v4/ethereum/non-archival/sepolia"
              l2_ep: "http://34.175.214.161:8500"
              bridge_ep: "http://34.175.214.161:8085"
              l1_pk_secret_name: "L1_SEPOLIA_PRIVATE_KEY"
              l2_pk_secret_name: "NETWORK5_PRIVATE_KEY"
              bridge_addr: "0xb566BE17B22404BD46F389030ec5592F8ffAde12"

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone eth-bench repository
        run: git clone --recurse-submodules -j8 https://github.com/xavier-romero/eth-bench.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and run benchmarks
        run: |
          #!/bin/bash
          cd eth-bench
          
          cat <<EOF > ./tmp_profiles.json
          {
            "profiles": {
              "${{ matrix.profile_name }}": {
                "description": "Nightly Tests",
                "node_url": "${{ matrix.l2_ep }}",
                "l1_ep": "${{ matrix.l1_ep }}",
                "bridge_addr": "${{ matrix.bridge_addr }}",
                "bridge_ep": "${{ matrix.bridge_ep }}",
                "funded_key": "${{ secrets[matrix.l2_pk_secret_name] }}"
                "l1_funded_key": "${{ matrix.secrets[matrix.l1_pk_secret_name] }}"
              }
            }
          }
          EOF

          export PROFILE=${{ matrix.profile }}

          docker compose build
          docker compose up --abort-on-container-exit --exit-code-from benchmark
          EXIT_CODE=$?
          docker compose down

          echo "Benchmark exit code for profile ${PROFILE}: $EXIT_CODE"
          exit $EXIT_CODE

      - name: Upload benchmark log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-log-${{ matrix.profile }}
          path: ./eth-bench/bench_${{ matrix.profile }}.log
