name: Nightly - ETH Bench

on:
  schedule:
    - cron: '0 1 * * *' # run at 1am to stagger tests
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [network5]

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone eth-bench repository
        run: git clone --recurse-submodules -j8 https://github.com/xavier-romero/eth-bench.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set PROFILE_UPPER environment variable
        run: |
          echo "PROFILE_UPPER=$(echo ${{ matrix.profile }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

      - name: Set RPC_URL and PRIVATE_KEY environment variables
        run: |
          echo "RPC_URL=${{ secrets[format('{0}_RPC_URL', env.PROFILE_UPPER)] }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY=${{ secrets[format('{0}_PRIVATE_KEY', env.PROFILE_UPPER)] }}" >> $GITHUB_ENV

      - name: Build and run benchmarks
        run: |
          #!/bin/bash
          cd eth-bench
          
          cat <<EOF > ./tmp_profiles.json
          {
            "profiles": {
              "${{ matrix.profile }}": {
                "description": "Nightly Tests",
                "node_url": "${{ env.RPC_URL }}",
                "funded_key": "${{ env.PRIVATE_KEY }}"
              }
            }
          }
          EOF

          export PROFILE=${{ matrix.profile }}

          docker compose build
          docker compose up --abort-on-container-exit --exit-code-from benchmark
          EXIT_CODE=$?
          docker compose down

          echo "Benchmark exit code for profile ${PROFILE}: $EXIT_CODE"
          exit $EXIT_CODE

      - name: Upload benchmark log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-log-${{ matrix.profile }}
          path: ./eth-bench/bench_${{ matrix.profile }}.log
