name: Unwinds tests
on:
  push:
    branches:
      - fixing-unwids-tests
  workflow_dispatch:

jobs:
  fixing-unwids-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout cdk-erigon
        uses: actions/checkout@v4
        with:
          path: cdk-erigon

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      # - name: Checkout cdk-erigon-lib
      #   uses: actions/checkout@v4
      #   with:
      #     repository: gateway-fm/cdk-erigon-lib
      #     ref: 5e3196248fde0e4d2c5f0b1c9819d360236e6f3a

      - name: Build
        run: |
          cd ./cdk-erigon
          make cdk-erigon

      - name: Update cdk-erigon-lib
        run: |
          erigonPath=$(pwd)
          cd /root/go/pkg/mod/github.com/gateway-fm
          cd $(ls ./ | grep cdk-erigon-lib | tail -1)
          cd ./kv
          "$erigonPath/cdk-erigon/zk/tests/unwinds/modify-cdk-erigon-lib.sh"
          cat ./tables.go

  
