name: Unwinds tests
on:
  push:
    branches:
      - fixing-unwids-tests
  workflow_dispatch:

jobs:
  fixing-unwids-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout cdk-erigon
        uses: actions/checkout@v4
        with:
          path: cdk-erigon

      - name: Bash
        run: ls -la

  
